"""startup new database


Revision ID: f5197a9b02f5
Revises: 
Create Date: 2020-05-31 12:54:33.755461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5197a9b02f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('pwHash', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_name'), 'admin', ['name'], unique=True)
    op.create_index(op.f('ix_admin_pwHash'), 'admin', ['pwHash'], unique=True)
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessionID', sa.Integer(), nullable=False),
    sa.Column('f1', sa.String(), nullable=True),
    sa.Column('f2', sa.String(), nullable=True),
    sa.Column('f3', sa.String(), nullable=True),
    sa.Column('f4', sa.String(), nullable=True),
    sa.Column('f5', sa.String(), nullable=True),
    sa.Column('f6', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_date'), 'answers', ['date'], unique=False)
    op.create_index(op.f('ix_answers_f1'), 'answers', ['f1'], unique=False)
    op.create_index(op.f('ix_answers_f2'), 'answers', ['f2'], unique=False)
    op.create_index(op.f('ix_answers_f3'), 'answers', ['f3'], unique=False)
    op.create_index(op.f('ix_answers_f4'), 'answers', ['f4'], unique=False)
    op.create_index(op.f('ix_answers_f5'), 'answers', ['f5'], unique=False)
    op.create_index(op.f('ix_answers_f6'), 'answers', ['f6'], unique=False)
    op.create_index(op.f('ix_answers_sessionID'), 'answers', ['sessionID'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_sessionID'), table_name='answers')
    op.drop_index(op.f('ix_answers_f6'), table_name='answers')
    op.drop_index(op.f('ix_answers_f5'), table_name='answers')
    op.drop_index(op.f('ix_answers_f4'), table_name='answers')
    op.drop_index(op.f('ix_answers_f3'), table_name='answers')
    op.drop_index(op.f('ix_answers_f2'), table_name='answers')
    op.drop_index(op.f('ix_answers_f1'), table_name='answers')
    op.drop_index(op.f('ix_answers_date'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_admin_pwHash'), table_name='admin')
    op.drop_index(op.f('ix_admin_name'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
